version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - admin_db 
    volumes:
      - ./:/app
    networks:
      - mm-network
      
  admin_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      admin_db:
        condition: service_healthy
        restart: true
    networks:
      - mm-network
       
  admin_db:
    image: mysql:5.7.22
    healthcheck:
      test: out=$$(mysqladmin ping -h admin_db -P 3306 -u root --password=root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33070:3306
    networks:
      - mm-network 
networks:
  mm-network:
    external: true
